# Generated by Django 4.0.5 on 2022-06-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titlu')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('draft', models.BooleanField(default=True, verbose_name='Proiect')),
                ('thumb', models.ImageField(upload_to='', verbose_name='Miniatură')),
                ('keywords', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Cuvinte cheie')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Data publicării')),
                ('content', models.TextField(verbose_name='Cuprins')),
            ],
            options={
                'verbose_name': 'Scris',
                'verbose_name_plural': 'articole',
                'ordering': ['-date'],
            },
        ),
    ]
